/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Planner,
  PlannerDto,
  PostApiPlannerParams
} from '../generated-api.schemas'



  export const getApiPlanner = <TData = AxiosResponse<Planner[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Planner`,options
    );
  }
export const postApiPlanner = <TData = AxiosResponse<void>>(
    plannerDto: PlannerDto,
    params?: PostApiPlannerParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Planner`,
      plannerDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const getApiPlannerPlannerId = <TData = AxiosResponse<Planner>>(
    plannerId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Planner/${plannerId}`,options
    );
  }
export const putApiPlannerPlannerId = <TData = AxiosResponse<void>>(
    plannerId: number,
    plannerDto: PlannerDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/Planner/${plannerId}`,
      plannerDto,options
    );
  }
export const deleteApiPlannerPlannerId = <TData = AxiosResponse<void>>(
    plannerId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/Planner/${plannerId}`,options
    );
  }
export const getApiPlannerPlannerIdProducts = <TData = AxiosResponse<Planner>>(
    plannerId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Planner/${plannerId}/products`,options
    );
  }
