/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Ingredient,
  IngredientDto
} from '../generated-api.schemas'



  export const getApiIngredient = <TData = AxiosResponse<Ingredient[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Ingredient`,options
    );
  }
export const postApiIngredient = <TData = AxiosResponse<void>>(
    ingredientDto: IngredientDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Ingredient`,
      ingredientDto,options
    );
  }
export const getApiIngredientIngredientId = <TData = AxiosResponse<Ingredient>>(
    ingredientId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Ingredient/${ingredientId}`,options
    );
  }
export const putApiIngredientIngredientId = <TData = AxiosResponse<void>>(
    ingredientId: number,
    ingredientDto: IngredientDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/Ingredient/${ingredientId}`,
      ingredientDto,options
    );
  }
export const deleteApiIngredientIngredientId = <TData = AxiosResponse<void>>(
    ingredientId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/Ingredient/${ingredientId}`,options
    );
  }
