/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  ShoppingList,
  ShoppingListDto,
  PostApiShoppingListParams,
  ProductFromList
} from '../generated-api.schemas'



  export const getApiShoppingList = <TData = AxiosResponse<ShoppingList[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/ShoppingList`,options
    );
  }
export const postApiShoppingList = <TData = AxiosResponse<void>>(
    shoppingListDto: ShoppingListDto,
    params?: PostApiShoppingListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/ShoppingList`,
      shoppingListDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const getApiShoppingListShoppingListId = <TData = AxiosResponse<ShoppingList>>(
    shoppingListId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/ShoppingList/${shoppingListId}`,options
    );
  }
export const putApiShoppingListShoppingListId = <TData = AxiosResponse<void>>(
    shoppingListId: number,
    shoppingListDto: ShoppingListDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/ShoppingList/${shoppingListId}`,
      shoppingListDto,options
    );
  }
export const deleteApiShoppingListShoppingListId = <TData = AxiosResponse<void>>(
    shoppingListId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/ShoppingList/${shoppingListId}`,options
    );
  }
export const getApiShoppingListShoppingListIdProducts = <TData = AxiosResponse<ProductFromList>>(
    shoppingListId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/ShoppingList/${shoppingListId}/products`,options
    );
  }
