/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import type { IngredientCategory } from './ingredientCategory';

export interface Ingredient {
  id?: number;
  name?: string | null;
  ingredientCategory?: IngredientCategory;
}
