/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */

export type MealTypes = typeof MealTypes[keyof typeof MealTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MealTypes = {
  '0': 0,
  '1': 1,
  '2': 2,
  '3': 3,
  '4': 4,
} as const;
