/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { Recipe } from './recipe';
import type { PlannerRecipe } from './plannerRecipe';

export interface Planner {
  id?: number;
  date?: string;
  user?: User;
  recipes?: Recipe[] | null;
  plannerRecipes?: PlannerRecipe[] | null;
}
