/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import type { Planner } from './planner';
import type { Recipe } from './recipe';

export interface PlannerRecipe {
  plannerId?: number;
  planner?: Planner;
  recipeId?: number;
  recipe?: Recipe;
}
