/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import type { MealTypes } from './mealTypes';

export type PostApiPlannerRecipeParams = { recipeId?: number; plannerId?: number; mealType?: MealTypes };
