/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import type { Unit } from './unit';
import type { Ingredient } from './ingredient';
import type { ShoppingList } from './shoppingList';

export interface ProductFromList {
  id?: number;
  unit?: Unit;
  ingredient?: Ingredient;
  shoppingList?: ShoppingList;
}
