/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import type { Unit } from './unit';

export interface ProductFromPlannerDto {
  id?: number;
  unit?: Unit;
  amount?: number;
}
