/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import type { Level } from './level';
import type { RecipeType } from './recipeType';
import type { User } from './user';
import type { WatchedRecipe } from './watchedRecipe';
import type { Planner } from './planner';
import type { PlannerRecipe } from './plannerRecipe';

export interface Recipe {
  id?: number;
  title?: string | null;
  level?: Level;
  time?: string | null;
  people?: number;
  photo?: string | null;
  recipeType?: RecipeType;
  owner?: User;
  watchers?: User[] | null;
  watchedRecipes?: WatchedRecipe[] | null;
  planners?: Planner[] | null;
  plannerRecipe?: PlannerRecipe[] | null;
}
