/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */

export type RecipeType = typeof RecipeType[keyof typeof RecipeType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecipeType = {
  '0': 0,
  '1': 1,
  '2': 2,
} as const;
