/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export interface ShoppingList {
  id?: number;
  title?: string | null;
  userId?: number;
  user?: User;
}
