/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */

export interface StepDto {
  id?: number;
  stepNumber?: number;
  description?: string | null;
  photo?: string | null;
}
