/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */

export interface UserCommentDto {
  id?: number;
  rating?: number;
  commentText?: string | null;
}
