/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import type { Recipe } from './recipe';
import type { WatchedRecipe } from './watchedRecipe';

export interface User {
  id?: number;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  password?: string | null;
  photo?: string | null;
  recipes?: Recipe[] | null;
  watchedRecipes?: WatchedRecipe[] | null;
}
