/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { Recipe } from './recipe';

export interface UserComment {
  id?: number;
  rating?: number;
  commentText?: string | null;
  user?: User;
  recipe?: Recipe;
}
