/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */

export interface UserDto {
  id?: number;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  password?: string | null;
  imageUrl?: string | null;
}
