/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import type { Recipe } from './recipe';
import type { User } from './user';

export interface WatchedRecipe {
  recipeId?: number;
  recipe?: Recipe;
  userId?: number;
  user?: User;
}
