/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  ProductFromList,
  ProductFromListDto,
  PostApiProductFromListParams
} from '../generated-api.schemas'



  export const getApiProductFromList = <TData = AxiosResponse<ProductFromList[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/ProductFromList`,options
    );
  }
export const postApiProductFromList = <TData = AxiosResponse<void>>(
    productFromListDto: ProductFromListDto,
    params?: PostApiProductFromListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/ProductFromList`,
      productFromListDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const getApiProductFromListProductId = <TData = AxiosResponse<ProductFromList>>(
    productId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/ProductFromList/${productId}`,options
    );
  }
export const putApiProductFromListProductFromListId = <TData = AxiosResponse<void>>(
    productFromListId: number,
    productFromListDto: ProductFromListDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/ProductFromList/${productFromListId}`,
      productFromListDto,options
    );
  }
export const deleteApiProductFromListProductFromListId = <TData = AxiosResponse<void>>(
    productFromListId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/ProductFromList/${productFromListId}`,options
    );
  }
