/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  ProductFromPlanner,
  ProductFromPlannerDto,
  PostApiProductFromPlannerParams
} from '../generated-api.schemas'



  export const getApiProductFromPlanner = <TData = AxiosResponse<ProductFromPlanner[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/ProductFromPlanner`,options
    );
  }
export const postApiProductFromPlanner = <TData = AxiosResponse<void>>(
    productFromPlannerDto: ProductFromPlannerDto,
    params?: PostApiProductFromPlannerParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/ProductFromPlanner`,
      productFromPlannerDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const getApiProductFromPlannerProductId = <TData = AxiosResponse<ProductFromPlanner>>(
    productId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/ProductFromPlanner/${productId}`,options
    );
  }
export const putApiProductFromPlannerProductFromPlannerId = <TData = AxiosResponse<void>>(
    productFromPlannerId: number,
    productFromPlannerDto: ProductFromPlannerDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/ProductFromPlanner/${productFromPlannerId}`,
      productFromPlannerDto,options
    );
  }
export const deleteApiProductFromPlannerProductFromPlannerId = <TData = AxiosResponse<void>>(
    productFromPlannerId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/ProductFromPlanner/${productFromPlannerId}`,options
    );
  }
