/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  PlannerRecipe,
  PostApiPlannerRecipeParams,
  DeleteApiPlannerRecipeParams
} from '../generated-api.schemas'



  export const getApiPlannerRecipe = <TData = AxiosResponse<PlannerRecipe[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/PlannerRecipe`,options
    );
  }
export const postApiPlannerRecipe = <TData = AxiosResponse<void>>(
    params?: PostApiPlannerRecipeParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/PlannerRecipe`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const deleteApiPlannerRecipe = <TData = AxiosResponse<void>>(
    params?: DeleteApiPlannerRecipeParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/PlannerRecipe`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
