/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Step,
  StepDto,
  PostApiStepParams
} from '../generated-api.schemas'



  export const getApiStep = <TData = AxiosResponse<Step[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Step`,options
    );
  }
export const postApiStep = <TData = AxiosResponse<void>>(
    stepDto: StepDto,
    params?: PostApiStepParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Step`,
      stepDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const getApiStepStepId = <TData = AxiosResponse<Step>>(
    stepId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Step/${stepId}`,options
    );
  }
export const putApiStepStepId = <TData = AxiosResponse<void>>(
    stepId: number,
    stepDto: StepDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/Step/${stepId}`,
      stepDto,options
    );
  }
export const deleteApiStepStepId = <TData = AxiosResponse<void>>(
    stepId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/Step/${stepId}`,options
    );
  }
