/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  ProductFromRecipe,
  ProductFromRecipeDto,
  PostApiProductFromRecipeParams
} from '../generated-api.schemas'



  export const getApiProductFromRecipe = <TData = AxiosResponse<ProductFromRecipe[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/ProductFromRecipe`,options
    );
  }
export const postApiProductFromRecipe = <TData = AxiosResponse<void>>(
    productFromRecipeDto: ProductFromRecipeDto,
    params?: PostApiProductFromRecipeParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/ProductFromRecipe`,
      productFromRecipeDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const getApiProductFromRecipeProductId = <TData = AxiosResponse<ProductFromRecipe>>(
    productId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/ProductFromRecipe/${productId}`,options
    );
  }
export const putApiProductFromRecipeProductFromRecipeId = <TData = AxiosResponse<void>>(
    productFromRecipeId: number,
    productFromRecipeDto: ProductFromRecipeDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/ProductFromRecipe/${productFromRecipeId}`,
      productFromRecipeDto,options
    );
  }
export const deleteApiProductFromRecipeProductFromRecipeId = <TData = AxiosResponse<void>>(
    productFromRecipeId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/ProductFromRecipe/${productFromRecipeId}`,options
    );
  }
