export const IngredientCategory = [
  "alkohole",
  "luźne artykuły",
  "mięso i wędliny",
  "konserwy",
  "mrożonki i lody",
  "nabiał",
  "przyprawy",
  "zboże i musli",
  "ryby",
  "słodycze i przekąski",
  "tłuszcze",
  "warzywa i owoce",
  "pieczywo",
  "inne",
];
