/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  UserComment,
  UserCommentDto,
  PostApiUserCommentParams
} from '../generated-api.schemas'



  export const getApiUserComment = <TData = AxiosResponse<UserComment[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/UserComment`,options
    );
  }
export const postApiUserComment = <TData = AxiosResponse<void>>(
    userCommentDto: UserCommentDto,
    params?: PostApiUserCommentParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/UserComment`,
      userCommentDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const getApiUserCommentUserCommentId = <TData = AxiosResponse<UserComment>>(
    userCommentId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/UserComment/${userCommentId}`,options
    );
  }
export const putApiUserCommentUserCommentId = <TData = AxiosResponse<void>>(
    userCommentId: number,
    userCommentDto: UserCommentDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/UserComment/${userCommentId}`,
      userCommentDto,options
    );
  }
export const deleteApiUserCommentUserCommentId = <TData = AxiosResponse<void>>(
    userCommentId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/UserComment/${userCommentId}`,options
    );
  }
