/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  WatchedRecipe,
  PostApiWatchedRecipeParams,
  DeleteApiWatchedRecipeParams
} from '../generated-api.schemas'



  export const getApiWatchedRecipe = <TData = AxiosResponse<WatchedRecipe[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/WatchedRecipe`,options
    );
  }
export const postApiWatchedRecipe = <TData = AxiosResponse<void>>(
    params?: PostApiWatchedRecipeParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/WatchedRecipe`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const deleteApiWatchedRecipe = <TData = AxiosResponse<void>>(
    params?: DeleteApiWatchedRecipeParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/WatchedRecipe`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
