/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * culinaryApp
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  Recipe,
  RecipeDto,
  PostApiRecipeParams,
  Step,
  UserComment
} from '../generated-api.schemas'



  export const getApiRecipe = <TData = AxiosResponse<Recipe[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Recipe`,options
    );
  }
export const postApiRecipe = <TData = AxiosResponse<void>>(
    recipeDto: RecipeDto,
    params?: PostApiRecipeParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/Recipe`,
      recipeDto,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export const getApiRecipeRecipeId = <TData = AxiosResponse<Recipe>>(
    recipeId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Recipe/${recipeId}`,options
    );
  }
export const putApiRecipeRecipeId = <TData = AxiosResponse<void>>(
    recipeId: number,
    recipeDto: RecipeDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/Recipe/${recipeId}`,
      recipeDto,options
    );
  }
export const deleteApiRecipeRecipeId = <TData = AxiosResponse<void>>(
    recipeId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/Recipe/${recipeId}`,options
    );
  }
export const getApiRecipeRecipeIdRating = <TData = AxiosResponse<number>>(
    recipeId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Recipe/${recipeId}/rating`,options
    );
  }
export const getApiRecipeRecipeIdSteps = <TData = AxiosResponse<Step[]>>(
    recipeId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Recipe/${recipeId}/steps`,options
    );
  }
export const getApiRecipeRecipeIdComments = <TData = AxiosResponse<UserComment[]>>(
    recipeId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/Recipe/${recipeId}/comments`,options
    );
  }
